[package]
name = "axum-limit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
axum-core = "0.4.3"
axum-test = "14.8.0"
dashmap = "5.5.3"
http = "1.1.0"
tokio = { version = "1.37.0", features = ["sync"] }

[dev-dependencies]
axum = "0.7.5"
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
